# Generated by Django 5.0 on 2024-08-30 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_operatingsystem_options'),
        ('resource', '0002_alter_host_cpu_cores_alter_host_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='operating_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.operatingsystem', verbose_name='操作系统'),
        ),
    ]
