# Generated by Django 5.0 on 2024-08-30 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_alter_host_operating_system'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='operating_system',
            new_name='os',
        ),
    ]
