# Generated by Django 5.0 on 2024-08-30 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0004_rename_operating_system_host_os'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='os',
            new_name='operating_system',
        ),
    ]
