# Generated by Django 5.0 on 2024-08-30 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_environment'),
        ('resource', '0005_rename_os_host_operating_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='environment',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='common.environment', verbose_name='环境'),
            preserve_default=False,
        ),
    ]
