# Generated by Django 5.0 on 2024-08-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_project'),
        ('resource', '0007_host_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='projects',
            field=models.ManyToManyField(blank=True, to='common.project', verbose_name='项目'),
        ),
    ]
