# Generated by Django 5.0 on 2024-09-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0009_alter_host_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='ip_address',
            field=models.GenericIPAddressField(default='10.1.0.0', verbose_name='IP地址'),
        ),
    ]
