# Generated by Django 5.0 on 2024-09-05 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_project_users'),
        ('resource', '0010_alter_host_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='projects',
        ),
        migrations.AddField(
            model_name='host',
            name='projects',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='common.project', verbose_name='项目'),
            preserve_default=False,
        ),
    ]
