# Generated by Django 5.0 on 2024-09-05 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0011_remove_host_projects_host_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='projects',
            new_name='project',
        ),
    ]
