# Generated by Django 5.0 on 2024-08-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Red Hat Enterprise Linux', max_length=100, unique=True, verbose_name='名称')),
                ('version', models.CharField(default='9.0', max_length=50, verbose_name='版本')),
            ],
        ),
    ]
