# Generated by Django 5.0 on 2024-08-30 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_operatingsystem_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operatingsystem',
            options={'verbose_name': '操作系统', 'verbose_name_plural': '操作系统'},
        ),
    ]
