# Generated by Django 5.0 on 2024-09-04 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_city_province_district_city_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='common.province'),
            preserve_default=False,
        ),
    ]
