# Generated by Django 5.0 on 2024-09-04 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_district_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='city',
        ),
        migrations.RemoveField(
            model_name='district',
            name='province',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
