# Generated by Django 5.0 on 2024-08-29 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySQL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='实例名称')),
                ('port', models.IntegerField(default=3306, verbose_name='端口号')),
                ('user', models.CharField(max_length=100, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('database', models.CharField(max_length=100, verbose_name='数据库名称')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.host', verbose_name='主机')),
            ],
            options={
                'verbose_name': 'MySQL',
                'verbose_name_plural': 'MySQL',
            },
        ),
    ]
