# Generated by Django 5.0 on 2024-08-30 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MySQL',
        ),
    ]
