# Generated by Django 5.0 on 2024-08-30 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0002_delete_mysql'),
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySQL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField(default=3306, help_text='MySQL 实例的端口号')),
                ('username', models.CharField(help_text='连接 MySQL 实例的用户名', max_length=255)),
                ('encrypted_password', models.CharField(help_text='加密的密码', max_length=255)),
                ('database_name', models.CharField(help_text='数据库名称', max_length=255)),
                ('version', models.CharField(help_text='MySQL 版本号', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录更新时间')),
                ('host', models.ForeignKey(help_text='关联的主机', on_delete=django.db.models.deletion.CASCADE, to='resource.host')),
            ],
            options={
                'verbose_name': 'MySQL',
                'verbose_name_plural': 'MySQL',
            },
        ),
    ]
