# Generated by Django 5.0 on 2024-08-30 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_initial'),
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysql',
            name='encrypted_password',
        ),
        migrations.AddField(
            model_name='mysql',
            name='password',
            field=models.CharField(default='', max_length=255, verbose_name='密码'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mysql',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='mysql',
            name='database_name',
            field=models.CharField(max_length=255, verbose_name='数据库名称'),
        ),
        migrations.AlterField(
            model_name='mysql',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.host', verbose_name='主机'),
        ),
        migrations.AlterField(
            model_name='mysql',
            name='port',
            field=models.IntegerField(default=3306, verbose_name='端口号'),
        ),
        migrations.AlterField(
            model_name='mysql',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='mysql',
            name='username',
            field=models.CharField(max_length=255, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='mysql',
            name='version',
            field=models.CharField(max_length=50, verbose_name='MySQL 版本号'),
        ),
    ]
