# Generated by Django 5.0 on 2024-08-30 05:54

import utils.encrypted_char_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_mysql_encrypted_password_mysql_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysql',
            name='password',
            field=utils.encrypted_char_field.EncryptedCharField(max_length=255, verbose_name='密码'),
        ),
    ]
