# Generated by Django 5.0 on 2024-09-03 02:18

import utils.encrypted_char_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_mysql_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysql',
            name='database_name',
            field=models.CharField(default='test_db', max_length=255, verbose_name='数据库名称'),
        ),
        migrations.AlterField(
            model_name='mysql',
            name='password',
            field=utils.encrypted_char_field.EncryptedCharField(default='password', max_length=255, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='mysql',
            name='username',
            field=models.CharField(default='root', max_length=255, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='mysql',
            name='version',
            field=models.CharField(default='8.0', max_length=50, verbose_name='MySQL 版本号'),
        ),
    ]
