# Generated by Django 5.0 on 2024-09-03 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_remove_mysql_database_name'),
        ('common', '0005_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysql',
            name='environment',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='common.environment', verbose_name='环境'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mysql',
            name='project',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='common.project', verbose_name='项目'),
            preserve_default=False,
        ),
    ]
