# Generated by Django 5.0 on 2024-09-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_mysql_environment_mysql_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysql',
            name='database_name',
            field=models.CharField(default='database_name', max_length=255, verbose_name='数据库名称'),
        ),
    ]
