# Generated by Django 5.0 on 2024-09-04 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_alter_mysql_environment'),
        ('common', '0007_district_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysql',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.environment', verbose_name='环境'),
        ),
    ]
