# Generated by Django 5.0 on 2024-09-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_alter_mysql_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysql',
            name='role',
            field=models.CharField(choices=[('PRIMARY', 'PRIMARY'), ('SECONDARY', 'SECONDARY')], default='PRIMARY', max_length=50, verbose_name='角色'),
        ),
    ]
