# Generated by Django 5.0 on 2024-09-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_mysql_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysql',
            name='version',
            field=models.CharField(default='8.0', max_length=50, verbose_name='版本号'),
        ),
    ]
