name: Build and Push HQCMDB Repo Docker Image to ACR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Alibaba Cloud Container Registry
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login --username=${{ secrets.ACR_USERNAME }} --password-stdin registry.cn-shenzhen.aliyuncs.com

      - name: Build and push Docker image
        run: |
          DATE_TAG=$(date +'%Y%m%d')
          REPO_NAME=${{ github.repository }}
          docker build -t registry.cn-shenzhen.aliyuncs.com/${REPO_NAME}:${DATE_TAG} .
          docker push registry.cn-shenzhen.aliyuncs.com/${REPO_NAME}:${DATE_TAG}
